// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiotqtgmyswcalxbinkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpb3RxdGdteXN3Y2FseGJpbmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzQ1ODYsImV4cCI6MjA2NDE1MDU4Nn0.h1qdTR5O4z4vlQBnaYFlQaWKBBDWmDFrAeqwBM8cjIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);